type: view
name: products
model_name: zenlytic_managed
sql_table_name: products
fields:
  - name: product_id
    field_type: dimension
    type: number
    primary_key: true
    searchable: true
    sql: ${TABLE}."PRODUCT_ID"
    synonyms: []
    tiers: null

  - name: name
    field_type: dimension
    type: string
    sql: ${TABLE}."NAME"
    searchable: true
