name: products_dnd2
type: view
model_name: zenlytic_managed
sql_table_name: products_dnd1
default_date: release_date
fields:
  - name: product_id
    field_type: dimension
    type: string
    sql: ${TABLE}."PRODUCT_ID"
    searchable: true
  - name: name
    field_type: dimension
    type: string
    sql: ${TABLE}."NAME"
    searchable: true
  - name: category
    field_type: dimension
    type: string
    sql: ${TABLE}."CATEGORY"
    searchable: true
  - name: manufacturer
    field_type: dimension
    type: string
    sql: ${TABLE}."MANUFACTURER"
    searchable: true
  - name: price
    field_type: dimension
    type: number
    sql: ${TABLE}."PRICE"
    searchable: true
  - name: stock_quantity
    field_type: dimension
    type: number
    sql: ${TABLE}."STOCK_QUANTITY"
    searchable: true
  - name: scale
    field_type: dimension
    type: string
    sql: ${TABLE}."SCALE"
    searchable: true
  - name: material
    field_type: dimension
    type: string
    sql: ${TABLE}."MATERIAL"
    searchable: true
  - name: description
    field_type: dimension
    type: string
    sql: ${TABLE}."DESCRIPTION"
    searchable: true
  - name: release_date
    field_type: dimension_group
    type: time
    sql: ${TABLE}."RELEASE_DATE"
    timeframes:
      - date
      - week
      - month
      - quarter
      - year
      - day_of_year
      - week_of_year
      - month_of_year
