type: topic
base_view: customers
model_name: pure_organics
label: Customers
description: Customer data
zoe_description: Customer data
hidden: false
views:
  customers:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: ${customers.CUSTOMER_ID}=${customers.CUSTOMER_ID}
