base_view: legislators
name: legislators
model_name: zenlytic_managed
label: Legislators
description: ''
views:
  votes:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${legislators.legislator_id}=${votes.legislator_id}
  bills:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${legislators.legislator_id}=${bills.sponsor_id}
type: topic
