base_view: marvel_rivals_heroes
name: marvel_rivals_heroes
model_name: zenlytic_managed
label: Marvel Rivals Heroes
description: ''
views:
  marvel_rivals_abilities:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${marvel_rivals_heroes.hero_id}=${marvel_rivals_abilities.hero_id}
type: topic
