base_view: movies
model_name: zenlytic_managed
label: Movies
description: ''
views:
  showtimes:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${movies.movie_id}=${showtimes.movie_id}
  bookings:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${showtimes.showtime_id}=${bookings.showtime_id}
  movie_customers:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: ${bookings.customer_id}=${movie_customers.customer_id}
type: topic
