base_view: sales
label: Sales
model_name: zenlytic_managed
views:
  products:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: ${sales.product_id}=${products.product_id}
type: topic
