base_view: weather_stations
name: weather_stations
model_name: zenlytic_managed
label: Weather Stations
description: ''
views:
  maintenance_records:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${weather_stations.station_id}=${maintenance_records.station_id}
type: topic
